[package]
name = "brainfuck-interpreter"
version = "0.1.0"
authors = ["RÃ©mi Blaise <pro@remi-blaise.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1.1"
